# based on https://github.com/realark/cl-sample-game/blob/master/azure-pipelines.yaml

trigger:
- master

variables:
  LISP: sbcl-bin
  ROSWELL_ZIP: https://ci.appveyor.com/api/projects/snmsts/roswell-en89n/artifacts/Roswell-x86_64.zip?branch=master&job=Environment%3A%20MSYS2_ARCH%3Dx86_64,%20MSYS2_BITS%3D64,%20MSYSTEM%3DMINGW64,%20METHOD%3Dcross


jobs:
  - job: 'Test'
    strategy:
      matrix:
        win:
          target: 'x86_64-windows-10'
          imageName: 'windows-2022'
    pool:
      vmImage: $(imageName)
    steps:
      - pwsh: Invoke-WebRequest -Uri $Env:ROSWELL_ZIP -OutFile Roswell.zip
        displayName: Download roswell
      - script: |
            set PATH=%PATH%;%USERPROFILE%\roswell\
            7z x -o%USERPROFILE% Roswell.zip
            ros install %LISP%
            ros config
            mkdir "%LOCALAPPDATA%\config\common-lisp\source-registry.conf.d\"
            set "dir=%AGENT_BUILDDIRECTORY:\=/%"
            echo (:tree "%dir%") > "%LOCALAPPDATA%\config\common-lisp\source-registry.conf.d\ci.conf"
        displayName: Unzip and configure
      - script: |
            set PATH=%PATH%;%USERPROFILE%\roswell\
            ros -Q -- roswell/run-fiveam.ros -l ci-utils/test :azure-pipelines-tests :base-tests :noncoveralls-tests
        displayName: Run tests